In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
ser = pd.Series([8,3,6,5,1],index = ["b","d","c","a","e"])

In [51]:
# series indexing and slicing

In [52]:
ser

b    8
d    3
c    6
a    5
e    1
dtype: int64

In [53]:
ser[1:5]

d    3
c    6
a    5
e    1
dtype: int64

In [54]:
# sort series by index

In [55]:
ser.sort_index()

a    5
b    8
c    6
d    3
e    1
dtype: int64

In [56]:
# sort seris by values

In [57]:
ser.sort_values()

e    1
d    3
a    5
c    6
b    8
dtype: int64

In [58]:
# aggregating in series

In [59]:
ser.mean()

4.6

In [60]:
ser.sum()

23

In [61]:
ser.dtype

dtype('int64')

In [62]:
# Create dataframe from series

In [63]:
df_ser = pd.DataFrame(ser)

In [64]:
df_ser

   0
b  8
d  3
c  6
a  5
e  1

In [65]:
df_ser.dtypes

0    int64
dtype: object

In [66]:
# Dataframe Manupulation

In [67]:
df = pd.read_csv("ny_weather.csv")

In [68]:
# Dataframe properties

In [69]:
df.head()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy

In [70]:
df.tail()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
9,1/12/2016,35.0,NaN,53.0,29.85,10.0,6.0,NaN
10,1/13/2016,26.0,4.0,NaN,29.94,10.0,10.0,Rain
11,1/14/2016,NaN,12.0,47.0,NaN,NaN,NaN,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,NaN,Sunny

In [71]:
df.columns

Index(['Date', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'Event'],
      dtype='object')

In [72]:
# Dimensions of the dataset

In [73]:
df.ndim

2

In [74]:
# number of rows and columns

In [75]:
df.shape

(14, 8)

In [76]:
# Slicing and indexing using

In [77]:
# Access Elements

In [78]:
# use loc for getting elements from rows index 6 - 11 and columns Temperature ,Humidity, Event

In [79]:
df.head(2)

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny

In [80]:
df.loc[6:11,["Temperature","Humidity","Event"]]

    Temperature  Humidity Event
6          44.0      77.0   NaN
7           NaN       NaN  Snow
8          33.0      37.0   NaN
9          35.0      53.0   NaN
10         26.0       NaN  Rain
11          NaN      47.0  Rain

In [81]:
# use iloc for getting elements from rows index 6 - 11 and columns Temperature ,Humidity, Event

In [82]:
df.iloc[6:12,[1,3,7]]

    Temperature  Humidity Event
6          44.0      77.0   NaN
7           NaN       NaN  Snow
8          33.0      37.0   NaN
9          35.0      53.0   NaN
10         26.0       NaN  Rain
11          NaN      47.0  Rain

In [83]:
# Add column

In [84]:
df.head(2)

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny

In [85]:
values = np.arange(30,44)

In [86]:
values

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [87]:
df["new_col"] = values

In [93]:
df.head()

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event,new_col
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain,30
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny,31
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow,32
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain,33
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy,34

In [94]:
# Remove New column

In [95]:
df.drop("new_col",axis=1,inplace=True)

In [97]:
df

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,NaN,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,NaN,8.0,NaN
7,1/10/2016,NaN,46.0,NaN,NaN,4.0,NaN,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,NaN,NaN
9,1/12/2016,35.0,NaN,53.0,29.85,10.0,6.0,NaN
10,1/13/2016,26.0,4.0,NaN,29.94,10.0,10.0,Rain
11,1/14/2016,NaN,12.0,47.0,NaN,NaN,NaN,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,NaN,Sunny

In [39]:
# Add new row

In [98]:
df.loc[14] = ["1/1/2018",39,25,52,34,8,9,"Sunny"]

In [99]:
df

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,NaN,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,NaN,8.0,NaN
7,1/10/2016,NaN,46.0,NaN,NaN,4.0,NaN,Snow
8,1/11/2016,33.0,8.0,37.0,29.92,10.0,NaN,NaN
9,1/12/2016,35.0,NaN,53.0,29.85,10.0,6.0,NaN
10,1/13/2016,26.0,4.0,NaN,29.94,10.0,10.0,Rain
11,1/14/2016,NaN,12.0,47.0,NaN,NaN,NaN,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow
13,1/18/2016,25.0,6.0,53.0,29.83,9.0,NaN,Sunny
14,1/1/2018,39.0,25.0,52.0,34.00,8.0,9.0,Sunny

In [42]:
# Remove rows index 8 $ 13

In [103]:
df.drop([7,14],inplace=True)

In [104]:
df

,Date,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,1/1/2016,38.0,23.0,52.0,30.03,10.0,8.0,Rain
1,1/2/2016,36.0,18.0,46.0,30.02,10.0,7.0,Sunny
2,1/3/2016,NaN,NaN,47.0,29.86,10.0,8.0,Snow
3,1/6/2016,33.0,NaN,35.0,NaN,10.0,4.0,Rain
4,1/7/2016,39.0,11.0,33.0,30.28,10.0,2.0,Cloudy
5,1/8/2016,39.0,29.0,NaN,30.20,10.0,4.0,Sunny
6,1/9/2016,44.0,38.0,77.0,30.16,NaN,8.0,NaN
9,1/12/2016,35.0,NaN,53.0,29.85,10.0,6.0,NaN
10,1/13/2016,26.0,4.0,NaN,29.94,10.0,10.0,Rain
11,1/14/2016,NaN,12.0,47.0,NaN,NaN,NaN,Rain
12,1/17/2016,36.0,23.0,66.0,29.78,8.0,6.0,Snow

In [45]:
# set index as date column

In [111]:
df.set_index("Temperature",inplace=True)

In [112]:
# reset index to default

In [113]:
df.reset_index(inplace=True)

In [114]:
df

,Temperature,Date,index,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,38.0,1/1/2016,0,23.0,52.0,30.03,10.0,8.0,Rain
1,36.0,1/2/2016,1,18.0,46.0,30.02,10.0,7.0,Sunny
2,NaN,1/3/2016,2,NaN,47.0,29.86,10.0,8.0,Snow
3,33.0,1/6/2016,3,NaN,35.0,NaN,10.0,4.0,Rain
4,39.0,1/7/2016,4,11.0,33.0,30.28,10.0,2.0,Cloudy
5,39.0,1/8/2016,5,29.0,NaN,30.20,10.0,4.0,Sunny
6,44.0,1/9/2016,6,38.0,77.0,30.16,NaN,8.0,NaN
7,35.0,1/12/2016,9,NaN,53.0,29.85,10.0,6.0,NaN
8,26.0,1/13/2016,10,4.0,NaN,29.94,10.0,10.0,Rain
9,NaN,1/14/2016,11,12.0,47.0,NaN,NaN,NaN,Rain
10,36.0,1/17/2016,12,23.0,66.0,29.78,8.0,6.0,Snow

In [50]:
# fill na with mean values of each column

In [116]:
df.describe()

,Temperature,index,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH
count,9.000000,11.000000,8.000000,9.000000,9.000000,9.000000,10.000000
mean,36.222222,5.727273,19.750000,50.666667,30.013333,9.777778,6.300000
std,4.944132,4.197402,10.872639,13.883443,0.172409,0.666667,2.406011
min,26.000000,0.000000,4.000000,33.000000,29.780000,8.000000,2.000000
25%,35.000000,2.500000,11.750000,46.000000,29.860000,10.000000,4.500000
50%,36.000000,5.000000,20.500000,47.000000,30.020000,10.000000,6.500000
75%,39.000000,9.500000,24.500000,53.000000,30.160000,10.000000,8.000000
max,44.000000,12.000000,38.000000,77.000000,30.280000,10.000000,10.000000

In [117]:
df.mean(numeric_only=True)

Temperature             36.222222
index                    5.727273
DewPoint                19.750000
Humidity                50.666667
Sea Level PressureIn    30.013333
VisibilityMiles          9.777778
WindSpeedMPH             6.300000
dtype: float64

In [118]:
df['Temperature'].mean()

36.22222222222222

In [119]:
df.Temperature.mean()

36.22222222222222

In [121]:
df.isnull().sum()

Temperature             2
Date                    0
index                   0
DewPoint                3
Humidity                2
Sea Level PressureIn    2
VisibilityMiles         2
WindSpeedMPH            1
Event                   2
dtype: int64

In [122]:
df.fillna({"Temperature":36.5,"DewPoint":22.9,"Humidity":50.8,"Sea Level PressureIn":30.4,"VisibilityMiles":9.09,
           "WindSpeedMPH":6.54},inplace=True)

In [123]:
df.isnull().sum()

Temperature             0
Date                    0
index                   0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
Event                   2
dtype: int64

In [53]:
# drop remaining null values

In [124]:
df.dropna(inplace=True)

In [125]:
df

,Temperature,Date,index,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event
0,38.0,1/1/2016,0,23.0,52.0,30.03,10.00,8.00,Rain
1,36.0,1/2/2016,1,18.0,46.0,30.02,10.00,7.00,Sunny
2,36.5,1/3/2016,2,22.9,47.0,29.86,10.00,8.00,Snow
3,33.0,1/6/2016,3,22.9,35.0,30.40,10.00,4.00,Rain
4,39.0,1/7/2016,4,11.0,33.0,30.28,10.00,2.00,Cloudy
5,39.0,1/8/2016,5,29.0,50.8,30.20,10.00,4.00,Sunny
8,26.0,1/13/2016,10,4.0,50.8,29.94,10.00,10.00,Rain
9,36.5,1/14/2016,11,12.0,47.0,30.40,9.09,6.54,Rain
10,36.0,1/17/2016,12,23.0,66.0,29.78,8.00,6.00,Snow

In [56]:
# group by Event and calculate average temperature

In [126]:
df.groupby("Event")[["Temperature"]].mean()

        Temperature
Event
Cloudy       39.000
Rain         33.375
Snow         36.250
Sunny        37.500

In [58]:
# Use apply function to convert visiblitymiles into km

In [127]:
df["visibilitykm"] = df["VisibilityMiles"].apply(lambda x: x*1.6 )

In [128]:
df

,Temperature,Date,index,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,Event,visibilitykm
0,38.0,1/1/2016,0,23.0,52.0,30.03,10.00,8.00,Rain,16.000
1,36.0,1/2/2016,1,18.0,46.0,30.02,10.00,7.00,Sunny,16.000
2,36.5,1/3/2016,2,22.9,47.0,29.86,10.00,8.00,Snow,16.000
3,33.0,1/6/2016,3,22.9,35.0,30.40,10.00,4.00,Rain,16.000
4,39.0,1/7/2016,4,11.0,33.0,30.28,10.00,2.00,Cloudy,16.000
5,39.0,1/8/2016,5,29.0,50.8,30.20,10.00,4.00,Sunny,16.000
8,26.0,1/13/2016,10,4.0,50.8,29.94,10.00,10.00,Rain,16.000
9,36.5,1/14/2016,11,12.0,47.0,30.40,9.09,6.54,Rain,14.544
10,36.0,1/17/2016,12,23.0,66.0,29.78,8.00,6.00,Snow,12.800

In [133]:
students = pd.read_csv("students.csv")

In [134]:
professors = pd.read_csv("professors.csv")

In [132]:
students.to_csv("C:\\Users\\Lenovo\\Desktop\\BIA_Material\\BIA_DS_Material\\Data_Science_project1\\students.csv",header=True,index=False)

In [135]:
students = pd.read_csv("students.csv")

In [139]:
students

   id_number               Name  Age Gender
0        204        James Smith   26      M
1        202    Maria Rodriguez   22      F
2        264        David Smith   24      M
3        136    Patricia Garcia   21      F
4        238  Jessica Hernandez   25      F

In [66]:
professors.to_csv("professors.csv",index=False,header=True)

In [140]:
professors  = pd.read_csv("professors.csv")

In [141]:
professors

         Prof_name  id_number Department
0     Thomas Smith        204        ECE
1  Margaret Garcia        264         EE
2    James Johnson        108        CSE
3   Richard Miller        238         ME
4   Margaret MOORE        136         CE

In [142]:
pd.concat([students, professors], ignore_index = True)

   id_number               Name   Age Gender        Prof_name Department
0        204        James Smith  26.0      M              NaN        NaN
1        202    Maria Rodriguez  22.0      F              NaN        NaN
2        264        David Smith  24.0      M              NaN        NaN
3        136    Patricia Garcia  21.0      F              NaN        NaN
4        238  Jessica Hernandez  25.0      F              NaN        NaN
5        204                NaN   NaN    NaN     Thomas Smith        ECE
6        264                NaN   NaN    NaN  Margaret Garcia         EE
7        108                NaN   NaN    NaN    James Johnson        CSE
8        238                NaN   NaN    NaN   Richard Miller         ME
9        136                NaN   NaN    NaN   Margaret MOORE         CE

In [198]:
pd.merge(students, professors[['id_number', 'Prof_name']])

   id_number               Name  Age Gender        Prof_name
0        204        James Smith   26      M     Thomas Smith
1        264        David Smith   24      M  Margaret Garcia
2        136    Patricia Garcia   21      F   Margaret MOORE
3        238  Jessica Hernandez   25      F   Richard Miller

In [200]:
pd.merge(students, professors, how = 'left')

   id_number               Name  Age Gender        Prof_name Department
0        204        James Smith   26      M     Thomas Smith        ECE
1        202    Maria Rodriguez   22      F              NaN        NaN
2        264        David Smith   24      M  Margaret Garcia         EE
3        136    Patricia Garcia   21      F   Margaret MOORE         CE
4        238  Jessica Hernandez   25      F   Richard Miller         ME

In [201]:
pd.merge(students, professors, how = 'right')

   id_number               Name   Age Gender        Prof_name Department
0        204        James Smith  26.0      M     Thomas Smith        ECE
1        264        David Smith  24.0      M  Margaret Garcia         EE
2        108                NaN   NaN    NaN    James Johnson        CSE
3        238  Jessica Hernandez  25.0      F   Richard Miller         ME
4        136    Patricia Garcia  21.0      F   Margaret MOORE         CE

In [202]:
pd.merge(students, professors, how = 'outer')

   id_number               Name   Age Gender        Prof_name Department
0        204        James Smith  26.0      M     Thomas Smith        ECE
1        202    Maria Rodriguez  22.0      F              NaN        NaN
2        264        David Smith  24.0      M  Margaret Garcia         EE
3        136    Patricia Garcia  21.0      F   Margaret MOORE         CE
4        238  Jessica Hernandez  25.0      F   Richard Miller         ME
5        108                NaN   NaN    NaN    James Johnson        CSE

In [144]:
 pd.merge(students, professors, how='left', on='id_number')

   id_number               Name  Age Gender        Prof_name Department
0        204        James Smith   26      M     Thomas Smith        ECE
1        202    Maria Rodriguez   22      F              NaN        NaN
2        264        David Smith   24      M  Margaret Garcia         EE
3        136    Patricia Garcia   21      F   Margaret MOORE         CE
4        238  Jessica Hernandez   25      F   Richard Miller         ME