# Introduction to Statements, Expressions, and Indentation

# Statements
A statement is a complete line of code that performs a specific action. Examples include assignment statements, loop statements, conditional statements, and function calls.

## Assignment Statements: Assign a value to a variable.

In [1]:
# Example 1: Assigning a string to a variable
name = "Alice"
name

'Alice'

In [2]:
#Example 2: Assigning a value to a variable
x = 10
x

10

## Print Statements: Output information to the console.

In [4]:
# Example 1: Printing a String
print("Hello, World!")

Hello, World!

In [5]:
print("Bike")

Bike

In [6]:
print("Iam Happy")

Iam Happy

In [7]:
print("Today We are started learning python")

Today We are started learning python

## Conditional Statements: Control the flow of execution based on conditions

In [13]:
x=4
X=9

In [14]:
x+X

13

In [9]:
# example 1
x = 4

In [16]:
if x>5:
    print("x is smarter")
else:
    print("x is not smarter")

x is not smarter

In [1]:

# Conditional statement
if x > 5:
    print("x is greater than 5")
else:
    print("x is not greater than 5")

x is greater than 5

In [2]:
x>7

False

In [18]:
# Example 2 : Checking if a person's age is eligible for voting
age = 19
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote yet.")

You are eligible to vote.

## Loop Statements: Execute a block of code repeatedly.

In [29]:
# Example 1: Using a for loop to iterate over a sequence of numbers
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [28]:
# Example 2 : print numbers from 1 to 5
for i in range(1, 6):
    # Inside the loop, the current value of 'i' is printed
    print(i)

1
2
3
4
5

## Expressions

An expression is a combination of values, variables, and operators that can be evaluated to produce a result. Expressions can be part of statements.

In [30]:
# Assigning the value 5 to the variable x
x = 5  # 5 is an expression
x

5

In [31]:
# Assigning the result of the expression x + 3 to the variable y
# x + 3 is an expression
y = x + 3
y

8

## Indentation

Indentation refers to the spaces or tabs at the beginning of a line of code. 
In Python, indentation is not just for readability it is a syntactical element that defines the structure of your code.
Indentation is used to group statements into blocks

## Rules for Indentation

- Use consistent indentation throughout your code.
- The standard convention is to use four spaces for each level of indentation.
- Indentation is used to indicate the beginning and end of code blocks, such as those in loops and conditional statements.

In [33]:
#example
if x > 5:  # The if statement starts here and is followed by a colon (:)
    print("x is greater than 5")  # This line is indented with four spaces and is part of the if block
else:  # The else statement starts here and is followed by a colon (:)
    print("x is not greater than 5")  # This line is indented with four spaces and is part of the else block

x is not greater than 5

In [36]:
# Example: Using indentation in a for loop
for i in range(3):
    print(i)# The for loop starts here and is followed by a colon (:)
    print("Inside the loop")  # This line is indented with four spaces and is part of the loop
print("4p")  # This line is not indented and outside the loop

0
Inside the loop
1
Inside the loop
2
Inside the loop
4p

## Identifiers, Keywords & Comments

## Identifiers

Identifiers are names given to entities in a Python program. These entities can be variables, functions, classes, modules, or any other user-defined objects.
Identifiers are crucial for making your code readable and understandable.

## Rules for Identifiers

- Must begin with a letter (a-z, A-Z) or an underscore (_).
- The remaining characters can be letters, numbers, or underscores.
- Case-sensitive (e.g., variable and Variable are different).

In [36]:
# Example 1: Using identifiers for variable names

# Assigning a value to the variable 'x'
x = 5  # Here, 'x' is an identifier representing the variable name

# Printing the value of 'x'
print("The value of x is:", x)

The value of x is: 5

In [41]:
Diptanshu=10
diptanshu=25
Ram=11

Diptanshu+Ram

21

In [40]:
# Example 2: Using identifiers for variable names

# Assigning a value to the variable 'y'
y = 8  # Here, 'y' is an identifier representing the variable name

# Printing the value of 'y'
print("The value of y is:", y)

The value of y is: 8

## Keywords

Keywords are reserved words in Python that have special meanings and cannot be used as identifiers.
They are part of the Python language syntax and serve specific purposes in the code.

## Examples of Keywords:

## if, else, while, for, in, def, class, True, False, None, and, or, not, import, from, as, try, except, etc.

In [44]:
# Python code to check Keywords
import keyword 

# Print the list of keywords
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

## Comments

Comments are annotations in the code that are ignored by the Python interpreter. They are meant for human readers to add explanations, notes, or any information that can help understand the code.

- Single-line Comments: Begin with # and extend to the end of the line.
- #This is a single-line comment
- Multi-line Comments: Enclosed between triple-quotes (''' or """) and can span multiple lines.- '''This is a multi-line comment'''

Example

In [78]:
# This is a comment explaining the purpose of the following code
x = "Laptop"  # This is an inline comment about the variable
print(x)

Laptop

# Variables in Python

Variables in Python are used to store data values

### Variable Declaration:
### name = "John“
### age = 30
### Here, ‘name’ & ‘age’ are variables which stores the values – “John” & 30

### Rules of variables

- They can contain letters, digits, and underscores.
- They must start with a letter or an underscore (but not a digit).
- Variable names are case-sensitive.
- Avoid using Python keywords (reserved words) as variable names.

In [48]:
# Assigning a numerical value (10) to the variable 'number'
number = 10
print(number)  # Printing the value of the variable

10

In [49]:
# Assigning a string value ("Hello, World!") to the variable 'message'
message = "Hello, World!"
print(message)  # Printing the value of the variable

Hello, World!

In [337]:
2+3

5

In [3]:
a,b=20,20

In [13]:
def student(a,b):
    return a+b,a-b,a*b

In [12]:
student(a,b)

(40, 0, 400)

In [14]:
c,d=10,40

In [15]:
student(c,d)

(50, -30, 400)

In [6]:
a+b

40

In [339]:
add(34,56)

90

### Multiple assignments in Python allow you to assign values to multiple variables in a single line.

### x, y, z = 10, 20, 30
### This assigns 10 to x, 20 to y, and 30 to z

In [55]:
# Multiple assignments
x, y, z = 10, 20, 30

# Print the values of x, y, and z
print("x =", x)
print("y =", y)
print("z =", z)

x = 10
y = 20
z = 30

### Variable reuse in Python allows you to assign a new value to an existing variable, effectively overwriting its previous value.

### x = 5
### x = "Hello“
### In this example, x initially holds an integer but is later assigned a string.

In [56]:
# Variable reuse
x = 5
print("Initial value of x:", x)

# Reassigning a new value to the variable 'x'
x = 10
print("New value of x:", x)

Initial value of x: 5
New value of x: 10

# Fundamental Data Types

### Integer (int)

An integer is a numerical data type that represents whole numbers. It does not include fractions or decimal points.

In [17]:
a = 12
print(type(a))   # To check the data type of a 
print(id(a))     # To check the id of a

<class 'int'>
140705360784152

In [59]:
# Assigning a positive integer value (42) to the variable 'positive_integer'
positive_integer = 42

# Assigning a negative integer value (-10) to the variable 'negative_integer'
negative_integer = -10

# Assigning zero (0) to the variable 'zero'
zero = 0

# Printing the values of the variables
print("Positive Integer:", positive_integer)
print("Negative Integer:", negative_integer)
print("Zero:", zero)

Positive Integer: 42
Negative Integer: -10
Zero: 0

### Integer Caches: Python caches a range of small integers (typically from -5 to 256)​

In [23]:
a = 42
b = 42
print(a is b)     # gives True
print(id(a), id(b))    # id of both a & b is same

True
140705360785112 140705360785112

In [21]:
x = 257
y = 257
print(x is y)    # gives False
print(id(x), id(y))    # id of both x & y may or may not be the same

False
2788320730736 2788320732336

In [73]:
x==y

True

### (Float)
### Floats are used to represent real numbers.

### Floats in Python are implemented as IEEE 754 double-precision floating-point numbers, which provide approximately 15-17 significant digits of precision

In [67]:
a = 1.5

# Printing the data type of 'a'
print(type(a))     # Output: <class 'float'> (indicating that 'a' is a float)

# Printing the memory address (ID) of 'a'
print(id(a))       # Output: Memory address of the float object '1.5'

<class 'float'>
1587726654480

In [65]:
# Assigning a floating-point value to the variable 'pi'
pi = 3.14159234567890123453457899906

# Printing the value of 'pi'
print("Value of pi:", pi)

Value of pi: 3.141592345678901

### Complex

- Complex numbers in Python are written as a+bj, where a is the real part, and b is the imaginary part
- Used in AC (circuit analysis), signal processing, and quantum mechanics.

In [66]:
z = 3 + 4j  # Where 3 is the real part, and 4 is the imaginary part.

# Printing the data type of 'z'
print(type(z))     # Output: <class 'complex'> (indicating that 'z' is a complex number)

# To check the id of 'z' (commented out)
# print(id(z))

<class 'complex'>

In [67]:
a = 10 + 12j  # Where 10 is the real part, and 12 is the imaginary part.

# Printing the data type of 'z'
print(type(a))     # Output: <class 'complex'> (indicating that 'z' is a complex number)

# To check the id of 'z' (commented out)
# print(id(a))

<class 'complex'>

### Boolean (bool)

- A boolean is a data type that represents one of two possible values: True or False
- Booleans are primarily used for logical operations and conditions.
- Used extensively in conditional statements, loops, and logical operations

In [68]:
# Using the bool() constructor to convert the integer value 20 to a boolean value
a = bool(20)

# Printing the boolean value 'a' and its data type
print(a, type(a))

True <class 'bool'>

In [69]:
# Using the bool() constructor to convert the integer value 0 to a boolean value
b = bool(0)

# Printing the boolean value 'b' and its data type
print(b, type(b))

False <class 'bool'>

### NoneType (None)

- NoneType is a special data type in Python that has only one value: None. 
- It is used to represent the absence of a value or a null value. 
- When a variable or a function returns None, it typically signifies that there is no valid data or no meaningful result.

### In this example, the variable result is assigned the value None, indicating that it has not been assigned a meaningful value or result yet
### result = None

# Strings in Python

- In Python, a string is a sequence of characters, and it is one of the fundamental data types in the language. 
- Strings are used to represent text and are treated as immutable sequences of Unicode code points.

### Strings can be declared using either single quotes (‘ ’) or double quotes (“ ”).

In [87]:
single_quoted = 'Hello, World!'
double_quoted = "Python is great!"
triple_quoted = '''This is a 
                   multi-line string.'''

print("Single quoted:", single_quoted)
print("Double quoted:", double_quoted)
print("Triple quoted:", triple_quoted)

Single quoted: Hello, World!
Double quoted: Python is great!
Triple quoted: This is a
                   multi-line string.

In [208]:
a= "This is Diptanshu's class"
type(a)
b= "He is teaching python"

print(a + ". " + b)

This is Diptanshu's class. He is teaching python

In [209]:
len(a)

25

In [211]:
a[3]

's'

### String Concatenation: You can concatenate (combine) strings using the + operator.

In [101]:
first_name = "Diptanshu"
last_name = "Bhardwaj"
full_name = first_name + " " + last_name  # Produces "John Doe"
print(full_name)

Diptanshu Bhardwaj

### String Length: You can find the length of a string using the len() function

In [111]:
text = "Python"
length = len(text)
print(length)

6

### String Indexing

### Strings are zero-indexed, meaning the first character has an index of 0, the second character has an index of 1, and so on.

In [112]:
text = "Python"

# Accessing the characters of the string using their indices
first_char = text[0]   # Accessing the first character
second_char = text[1]  # Accessing the second character
third_char = text[2]   # Accessing the third character

# Printing the characters along with their indices
print("First character (index 0):", first_char)
print("Second character (index 1):", second_char)
print("Third character (index 2):", third_char)

First character (index 0): P
Second character (index 1): y
Third character (index 2): t

### String Slicing

- Slicing allows you to extract a portion (substring) of a string by specifying a range of indices.
- The syntax for slicing is string[start:end:steps], where start is the index of the first character you want to include, and end is the index of the first character you want to exclude.

In [127]:
# Define the string variable 'text'
text = "Python"

# Slice the string from index 1 to 4 (exclusive) and assign it to 'sliced_text'
sliced_text = text[1:4]  # "yth" (from index 1 to 3)

# Print the sliced text along with a comment
print("Sliced text:", sliced_text)

Sliced text: yth

In [121]:
# Define the string variable 'text'
text = "Python"

# Slice the string using negative indices and assign it to 'sliced_text'
sliced_text = text[-4:-1]  # "th" (from the third-to-last to the second-to-last character)

# Print the sliced text along with a comment
print("Sliced text:", sliced_text)

Sliced text: tho

# String Methods

In [133]:
a=2+4j
type(a)

complex

In [134]:
b=str(a)
type(b)

str

In [130]:
print(b)

2.4

- Conversion Methods - str(): Converts an object into a string representation
- int(), float(), complex(): Converts a string to an integer, float, or complex number.¶

In [93]:
# Define an integer variable 'number'
number = 42

# Convert the integer 'number' to a string and assign it to 'str_number'
str_number = str(number)

# Print the converted string along with a comment
print("String representation of the number:", str_number)

String representation of the number: 42

### Case Conversion Methods

- upper(): Converts all characters in a string to uppercase.
- lower(): Converts all characters in a string to lowercase.
- capitalize(): Capitalizes the first character of a string.
- title(): Converts the first character of each word to uppercase.

In [135]:
a="Diptanshu"
type(a)

str

In [136]:
a.upper()

'DIPTANSHU'

In [137]:
a.lower()

'diptanshu'

In [96]:
# Define the string variable 'text'
text = "Python is Fun"

# Convert the string to uppercase and assign it to 'upper_text'
upper_text = text.upper()

# Convert the string to lowercase and assign it to 'lower_text'
lower_text = text.lower()

# Print the converted strings along with comments
print("Uppercase:", upper_text)
print("Lowercase:", lower_text)

Uppercase: PYTHON IS FUN
Lowercase: python is fun

### Stripping Methods

- strip(): Removes leading and trailing whitespace from a string.
- lstrip(): Removes leading whitespace.
- rstrip(): Removes trailing whitespace.

In [139]:
my_string = " Python is   fun! "
print(my_string)

 Python is   fun!

In [150]:
# Define the string variable 'my_string'
my_string = " Python is fun!"

# Strip leading and trailing whitespace characters from the string and assign it to 'stripped_string'
stripped_string = my_string.lstrip()

# Print the stripped string along with a comment
print("Stripped string:", stripped_string)

Stripped string: Python is fun!

### Search and Replace Methods

- find(): Returns the lowest index of a substring (or -1 if not found).
- index(): Similar to find() but raises an exception if the substring is not found.
- replace(): Replaces occurrences of a substring with another string.

In [205]:
sentence= "we are going to learn about function today"
index= sentence.find("is")

In [206]:
index

-1

In [200]:
sentence= "we are going to learn about function today"
index= sentence.index("is")

ValueError: substring not found

In [199]:
index

16

In [212]:
# Define the string variable 'sentence'
sentence = "Python is easy and Python is fun"

# Find the index of the first occurrence of "is" in the string and assign it to 'index'
index = sentence.find("is")

# Replace all occurrences of "Python" with "JavaScript" in the string and assign it to 'replaced_sentence'
replaced_sentence = sentence.replace("Python", "JavaScript")

# Print the replaced sentence along with a comment
print("Replaced sentence:", replaced_sentence)

Replaced sentence: JavaScript is easy and JavaScript is fun

### Counting Methods

### count(): Returns the number of occurrences of a substring in a string.

In [215]:
# Define the string variable 'sentence'
sentence = "Python is easy and Python is fun"

# Count the occurrences of the substring "is" in the string and assign it to 'count_is'
count_is = sentence.count("Python")

# Print the count along with a comment
print("Count of 'is':", count_is)

Count of 'is': 2

### Checking Methods

- startswith(): Checks if a string starts with a specified prefix.
- endswith(): Checks if a string ends with a specified suffix.
- isalpha(): Checks if all characters in a string are alphabetic.
- isdigit(): Checks if all characters in a string are digits.
- isalnum(): Checks if all characters in a string are alphanumeric.

In [219]:
# Define the string variable 'text'
text = "Today we are going to learn about user defined function"

# Check if the string starts with the prefix "Hello" and assign the result to 'starts_with_hello'
starts_with_hello = text.startswith("Today we are")

# Print the result along with a comment
print("Starts with 'Today we are':", starts_with_hello)

Starts with 'Today we are': True

### Splitting and Joining Methods

- split(): Splits a string into a list of substrings based on a specified delimiter.
- join(): Concatenates a list of strings into one string using a specified delimiter.

In [241]:
sentence ="Today we are going to learn about user defined function. We will also do handson exercise"
x=sentence.split(" ")

In [242]:
x

['Today',
 'we',
 'are',
 'going',
 'to',
 'learn',
 'about',
 'user',
 'defined',
 'function.',
 'We',
 'will',
 'also',
 'do',
 'handson',
 'exercise']

In [236]:
y= " ".join(x)

In [237]:
y

'Today we are going to learn about user defined function. We will also do handson exercise'

In [225]:
# Define the string variable 'sentence'
sentence = "Python is easy and fun"

# Split the string into words and assign the result to 'words'
words = sentence.split()  # Defaults to splitting on whitespace

# Join the words back into a single string with space as separator and assign it to 'joined_sentence'
joined_sentence = " ".join(words)

# Print the joined sentence along with a comment
print("Joined sentence:", joined_sentence)

Joined sentence: Python is easy and fun

### Formatting Methods

- format(): Formats a string by replacing placeholders with values.
- format_map(): Similar to format() but takes a mapping (a dictionary) as its argument.

In [245]:
# Define variables 'name' and 'age'
name = "Karthikeyan"
age = 21

course = "data science course"

# Format the string using placeholders {} and the format() method, and assign it to 'formatted_string'
formatted_string = "My name is {}, and I am {} years old. I am  taking {}".format(name, age, course)

# Print the formatted string along with a comment
print("Formatted string:", formatted_string)

Formatted string: My name is Karthikeyan, and I am 21 years old. I am  taking data science course

# Type Casting & Conversion

### bool(): Converts an object to a Boolean value.

In [107]:
# Define the variable 'value'
value = 0

# Convert the value to a boolean and assign it to 'bool_value'
bool_value = bool(value)

# Print the boolean value along with a comment
print("Boolean value:", bool_value)

Boolean value: False

### list(): Converts an iterable (e.g., tuple, string, or set) to a list.

In [261]:
my_list = [1,2,3,4,"Namita","Tanmayi","Aishwarya","Aishwarya"]

In [262]:
my_list[4]="Jyothi"

In [263]:
my_list

[1, 2, 3, 4, 'Jyothi', 'Tanmayi', 'Aishwarya', 'Aishwarya']

In [255]:
type(my_list)

list

In [270]:
my_tuple=(4,3,2,4,2,"Diptanshu")

In [271]:
type(my_tuple)

tuple

In [269]:
my_tuple[0]=5

TypeError: 'tuple' object does not support item assignment

In [273]:
change_tuple=list(my_tuple)

In [274]:
type(change_tuple)

list

In [275]:
change_tuple

[1, 2, 3]

In [284]:
fruits = ['apple', 'banana', 'cherry']
fruits.append("orange")

In [285]:
fruits

['apple', 'banana', 'cherry', 'orange']

In [272]:
# Define the tuple 'my_tuple'
my_tuple = (1, 2, 3)

# Convert the tuple to a list and assign it to 'my_list'
my_list = list(my_tuple)

# Print the converted list along with a comment
print("Converted list:", my_list)

Converted list: [1, 2, 3]

###  tuple(): Converts an iterable to a tuple.

In [109]:
# Define the list 'my_list'
my_list = [1, 2, 3]

# Convert the list to a tuple and assign it to 'my_tuple'
my_tuple = tuple(my_list)

# Print the converted tuple along with a comment
print("Converted tuple:", my_tuple)

Converted tuple: (1, 2, 3)

###   set(): Converts an iterable to a set.

In [110]:
# Define the list 'my_list'
my_list = [1, 2, 3, 3]

# Convert the list to a set and assign it to 'my_set'
my_set = set(my_list)

# Print the converted set along with a comment
print("Converted set:", my_set)

Converted set: {1, 2, 3}

### int(): Converts a number or a string containing a whole number to an integer.

In [111]:
# Define the string 'num_str'
num_str = "123.45"

# Convert the string to a float and assign it to 'num_float'
num_float = float(num_str)

# Print the converted float along with a comment
print("Converted float:", num_float)

Converted float: 123.45

### float(): Converts a number or a string containing a number to a floating-point number

In [112]:
# Define the string 'num_str'
num_str = "123.45"

# Convert the string to a float and assign it to 'num_float'
num_float = float(num_str)

# Print the converted float along with a comment
print("Converted float:", num_float)

Converted float: 123.45

###  str(): Converts an object to a string.

In [113]:
# Define the integer 'num_int'
num_int = 123

# Convert the integer to a string and assign it to 'num_str'
num_str = str(num_int)

# Print the converted string along with a comment
print("Converted string:", num_str)

Converted string: 123

In [288]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}

In [290]:
thisdict['brand']

'Ford'

In [292]:
thisdict.values()

dict_values(['Ford', 'Mustang', 1964, 'red'])

In [308]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.pop("year")
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang'}

In [282]:
student

{'name': 'Karthikeyan', 'age': 21, 'marks': 85}

In [298]:
my_list=[1,2,23,45,67,4,5,6,6,8,1]

In [299]:
set(my_list)

{1, 2, 4, 5, 6, 8, 23, 45, 67}

In [306]:
number={1,2,3,4,4}
number2={8,7,6}

number.update(number2)

In [304]:
number.add(5)

In [307]:
number

{1, 2, 3, 4, 6, 7, 8}

In [296]:
type(number)

set

In [297]:
number

{1, 2, 3, 4}

In [310]:
import sys

list_data = [1, 2, 3, 4]
tuple_data = (1, 2, 3, 4)

print(sys.getsizeof(list_data))
print(sys.getsizeof(tuple_data))

88
72

### dict(): Converts a sequence of key-value pairs as tuples into a dictionary.

In [114]:
# Define the list of tuples 'my_list'
my_list = [('a', 1), ('b', 2)]

# Convert the list of tuples to a dictionary and assign it to 'my_dict'
my_dict = dict(my_list)

# Print the converted dictionary along with a comment
print("Converted dictionary:", my_dict)

Converted dictionary: {'a': 1, 'b': 2}

### ord() and chr(): Convert a character to its Unicode code point and vice versa.

In [157]:
# Define the character 'char'
char = 'a'

# Get the Unicode code point of the character and assign it to 'unicode_value'
unicode_value = ord(char)

# Get the character from its Unicode code point and assign it to 'char_again'
char_again = chr(unicode_value)

# Print the Unicode code point of the character along with a comment
print("Unicode code point of", char, ":", unicode_value)

# Print the character obtained from its Unicode code point along with a comment
print("Character obtained from Unicode code point", unicode_value, ":", char_again)

Unicode code point of a : 97
Character obtained from Unicode code point 97 : a

In [311]:
a = 10
b = 5
result = a + b
print(result)

15

In [312]:
a = 10
b = 5
result = b - a
print(result)

-5

In [313]:
a = 10
b = 5
result = a * b
print(result)

50

In [314]:
a = 10
b = 5
result = a / b
print(result)

2.0

In [316]:
# Modulus (%)

# Gives the remainder after division

a = 10
b = 4
result = a % b
print(result)

2

In [317]:
# Real-life idea:
# Used to check even/odd numbers

print(10 % 2)  # 0 → even
print(7 % 2)   # 1 → odd

0
1

In [318]:
# Exponentiation (**)

# Raises a number to the power of another
a = 2
b = 3
result = a ** b
print(result)

8

In [319]:
a = 10
b = 10
print(a == b)

True

In [321]:
a = 7
b = 5
print(a != b)

True

In [173]:
a = 10
b = 5
print(a > b)

True

In [174]:
a = 5
b = 10
print(a < b)

True

In [175]:
a = 10
b = 10
print(a >= b)

True

In [176]:
a = 5
b = 10
print(a <= b)

True

In [177]:
x = 10
print(x)

10

In [324]:
x = 10
x += 1
print(x)

11

In [325]:
x = 10
x -= 3
print(x)

7

In [326]:
x = 10
x *= 2
print(x)

20

In [327]:
x = 10
x /= 2
print(x)

5.0

In [328]:
x = 10
x %= 3
print(x)

1

In [332]:
marks = 35
attendance = 80

print(marks >= 40 and attendance >= 75)

False

In [333]:
degree = False
experience = 6

print(degree or experience >= 5)

True

In [186]:
age = 16

if not age >= 18:
    print("Minor")

Minor

In [187]:
#same as
if age < 18:
    print("Minor")

Minor

In [336]:
#bit wise operator 
import pandas as pd

df = pd.DataFrame({
    "age": [20, 16, 30,21],
    "marks": [80, 60, 40,85]
})

df[(df["age"] >= 18) & (df["marks"] >= 50)]

   age  marks
0   20     80
3   21     85

In [334]:
#bit wise operator 
import pandas as pd

df = pd.DataFrame({
    "age": [20, 16, 30],
    "marks": [80, 60, 40]
})

In [335]:
df

   age  marks
0   20     80
1   16     60
2   30     40

In [189]:
(df["age"] >= 18) and (df["marks"] >= 50)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [192]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4

In [193]:
def my_function():
    x = 10   # local variable
    print(x)

my_function()

10

In [194]:
x = 50  # global variable

def show():
    print(x)

show()
print(x)

50
50